<?php

namespace ContainerUGCjMLX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DefaultController' shared autowired service.
     *
     * @return \App\Controller\DefaultController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DefaultController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/LiveMatchService.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client-contracts/HttpClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client/HttpClient.php';
        include_once \dirname(__DIR__, 4).'/src/Service/UserDataService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/UserGameHistoryService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/StoreItemsService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SignUpService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/LoginService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));
        $b = \Symfony\Component\HttpClient\HttpClient::create([], 6);
        $b->setLogger(($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
        $c = ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
        $d = new \App\Service\UserDataService($b, $c);

        $container->services['App\\Controller\\DefaultController'] = $instance = new \App\Controller\DefaultController(new \App\Service\LiveMatchService($a, $b, $c, $d), new \App\Service\UserGameHistoryService($b, $c, $d), $d, new \App\Service\StoreItemsService($b, $c, $a), new \App\Service\SignUpService($a, $d), new \App\Service\LoginService());

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'session' => ['privates', '.session.deprecated', 'get_Session_DeprecatedService', true],
        ], [
            'doctrine' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'session' => '.session.deprecated',
        ]))->withContext('App\\Controller\\DefaultController', $container));

        return $instance;
    }
}
