<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container14gG4ho\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container14gG4ho/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container14gG4ho.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container14gG4ho\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container14gG4ho\App_KernelDevDebugContainer([
    'container.build_hash' => '14gG4ho',
    'container.build_id' => '773751b1',
    'container.build_time' => 1638353189,
], __DIR__.\DIRECTORY_SEPARATOR.'Container14gG4ho');
