<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7PH3r2V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7PH3r2V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7PH3r2V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7PH3r2V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7PH3r2V\App_KernelDevDebugContainer([
    'container.build_hash' => '7PH3r2V',
    'container.build_id' => '6e4a1e4f',
    'container.build_time' => 1638538809,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7PH3r2V');
